//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2_Client.HotelReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Offer", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Offer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        private int maxPersonAmountField;
        
        private System.DateTime availabiltyDateField;
        
        private float priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] imageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int maxPersonAmount {
            get {
                return this.maxPersonAmountField;
            }
            set {
                if ((this.maxPersonAmountField.Equals(value) != true)) {
                    this.maxPersonAmountField = value;
                    this.RaisePropertyChanged("maxPersonAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime availabiltyDate {
            get {
                return this.availabiltyDateField;
            }
            set {
                if ((this.availabiltyDateField.Equals(value) != true)) {
                    this.availabiltyDateField = value;
                    this.RaisePropertyChanged("availabiltyDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public float price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TP2_Client.HotelReference.CreditCard CardField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public TP2_Client.HotelReference.CreditCard Card {
            get {
                return this.CardField;
            }
            set {
                if ((object.ReferenceEquals(this.CardField, value) != true)) {
                    this.CardField = value;
                    this.RaisePropertyChanged("Card");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditCard", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CreditCard : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CVVField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ExpirationDate {
            get {
                return this.ExpirationDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpirationDateField, value) != true)) {
                    this.ExpirationDateField = value;
                    this.RaisePropertyChanged("ExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CVV {
            get {
                return this.CVVField;
            }
            set {
                if ((object.ReferenceEquals(this.CVVField, value) != true)) {
                    this.CVVField = value;
                    this.RaisePropertyChanged("CVV");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HotelReference.HotelServiceSoap")]
    public interface HotelServiceSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément HelloWorldResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        TP2_Client.HotelReference.HelloWorldResponse HelloWorld(TP2_Client.HotelReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<TP2_Client.HotelReference.HelloWorldResponse> HelloWorldAsync(TP2_Client.HotelReference.HelloWorldRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément login de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FetchAvailableOffers", ReplyAction="*")]
        TP2_Client.HotelReference.FetchAvailableOffersResponse FetchAvailableOffers(TP2_Client.HotelReference.FetchAvailableOffersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FetchAvailableOffers", ReplyAction="*")]
        System.Threading.Tasks.Task<TP2_Client.HotelReference.FetchAvailableOffersResponse> FetchAvailableOffersAsync(TP2_Client.HotelReference.FetchAvailableOffersRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément login de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MakeReservation", ReplyAction="*")]
        TP2_Client.HotelReference.MakeReservationResponse MakeReservation(TP2_Client.HotelReference.MakeReservationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MakeReservation", ReplyAction="*")]
        System.Threading.Tasks.Task<TP2_Client.HotelReference.MakeReservationResponse> MakeReservationAsync(TP2_Client.HotelReference.MakeReservationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public TP2_Client.HotelReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(TP2_Client.HotelReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP2_Client.HotelReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(TP2_Client.HotelReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchAvailableOffersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchAvailableOffers", Namespace="http://tempuri.org/", Order=0)]
        public TP2_Client.HotelReference.FetchAvailableOffersRequestBody Body;
        
        public FetchAvailableOffersRequest() {
        }
        
        public FetchAvailableOffersRequest(TP2_Client.HotelReference.FetchAvailableOffersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FetchAvailableOffersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime start;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime end;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int persons;
        
        public FetchAvailableOffersRequestBody() {
        }
        
        public FetchAvailableOffersRequestBody(string login, string password, System.DateTime start, System.DateTime end, int persons) {
            this.login = login;
            this.password = password;
            this.start = start;
            this.end = end;
            this.persons = persons;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchAvailableOffersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchAvailableOffersResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP2_Client.HotelReference.FetchAvailableOffersResponseBody Body;
        
        public FetchAvailableOffersResponse() {
        }
        
        public FetchAvailableOffersResponse(TP2_Client.HotelReference.FetchAvailableOffersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FetchAvailableOffersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TP2_Client.HotelReference.Offer[] FetchAvailableOffersResult;
        
        public FetchAvailableOffersResponseBody() {
        }
        
        public FetchAvailableOffersResponseBody(TP2_Client.HotelReference.Offer[] FetchAvailableOffersResult) {
            this.FetchAvailableOffersResult = FetchAvailableOffersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MakeReservationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MakeReservation", Namespace="http://tempuri.org/", Order=0)]
        public TP2_Client.HotelReference.MakeReservationRequestBody Body;
        
        public MakeReservationRequest() {
        }
        
        public MakeReservationRequest(TP2_Client.HotelReference.MakeReservationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MakeReservationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public TP2_Client.HotelReference.Customer customer;
        
        public MakeReservationRequestBody() {
        }
        
        public MakeReservationRequestBody(string login, string password, int id, TP2_Client.HotelReference.Customer customer) {
            this.login = login;
            this.password = password;
            this.id = id;
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MakeReservationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MakeReservationResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP2_Client.HotelReference.MakeReservationResponseBody Body;
        
        public MakeReservationResponse() {
        }
        
        public MakeReservationResponse(TP2_Client.HotelReference.MakeReservationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MakeReservationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool MakeReservationResult;
        
        public MakeReservationResponseBody() {
        }
        
        public MakeReservationResponseBody(bool MakeReservationResult) {
            this.MakeReservationResult = MakeReservationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HotelServiceSoapChannel : TP2_Client.HotelReference.HotelServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelServiceSoapClient : System.ServiceModel.ClientBase<TP2_Client.HotelReference.HotelServiceSoap>, TP2_Client.HotelReference.HotelServiceSoap {
        
        public HotelServiceSoapClient() {
        }
        
        public HotelServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP2_Client.HotelReference.HelloWorldResponse TP2_Client.HotelReference.HotelServiceSoap.HelloWorld(TP2_Client.HotelReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            TP2_Client.HotelReference.HelloWorldRequest inValue = new TP2_Client.HotelReference.HelloWorldRequest();
            inValue.Body = new TP2_Client.HotelReference.HelloWorldRequestBody();
            TP2_Client.HotelReference.HelloWorldResponse retVal = ((TP2_Client.HotelReference.HotelServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP2_Client.HotelReference.HelloWorldResponse> TP2_Client.HotelReference.HotelServiceSoap.HelloWorldAsync(TP2_Client.HotelReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP2_Client.HotelReference.HelloWorldResponse> HelloWorldAsync() {
            TP2_Client.HotelReference.HelloWorldRequest inValue = new TP2_Client.HotelReference.HelloWorldRequest();
            inValue.Body = new TP2_Client.HotelReference.HelloWorldRequestBody();
            return ((TP2_Client.HotelReference.HotelServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP2_Client.HotelReference.FetchAvailableOffersResponse TP2_Client.HotelReference.HotelServiceSoap.FetchAvailableOffers(TP2_Client.HotelReference.FetchAvailableOffersRequest request) {
            return base.Channel.FetchAvailableOffers(request);
        }
        
        public TP2_Client.HotelReference.Offer[] FetchAvailableOffers(string login, string password, System.DateTime start, System.DateTime end, int persons) {
            TP2_Client.HotelReference.FetchAvailableOffersRequest inValue = new TP2_Client.HotelReference.FetchAvailableOffersRequest();
            inValue.Body = new TP2_Client.HotelReference.FetchAvailableOffersRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.start = start;
            inValue.Body.end = end;
            inValue.Body.persons = persons;
            TP2_Client.HotelReference.FetchAvailableOffersResponse retVal = ((TP2_Client.HotelReference.HotelServiceSoap)(this)).FetchAvailableOffers(inValue);
            return retVal.Body.FetchAvailableOffersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP2_Client.HotelReference.FetchAvailableOffersResponse> TP2_Client.HotelReference.HotelServiceSoap.FetchAvailableOffersAsync(TP2_Client.HotelReference.FetchAvailableOffersRequest request) {
            return base.Channel.FetchAvailableOffersAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP2_Client.HotelReference.FetchAvailableOffersResponse> FetchAvailableOffersAsync(string login, string password, System.DateTime start, System.DateTime end, int persons) {
            TP2_Client.HotelReference.FetchAvailableOffersRequest inValue = new TP2_Client.HotelReference.FetchAvailableOffersRequest();
            inValue.Body = new TP2_Client.HotelReference.FetchAvailableOffersRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.start = start;
            inValue.Body.end = end;
            inValue.Body.persons = persons;
            return ((TP2_Client.HotelReference.HotelServiceSoap)(this)).FetchAvailableOffersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP2_Client.HotelReference.MakeReservationResponse TP2_Client.HotelReference.HotelServiceSoap.MakeReservation(TP2_Client.HotelReference.MakeReservationRequest request) {
            return base.Channel.MakeReservation(request);
        }
        
        public bool MakeReservation(string login, string password, int id, TP2_Client.HotelReference.Customer customer) {
            TP2_Client.HotelReference.MakeReservationRequest inValue = new TP2_Client.HotelReference.MakeReservationRequest();
            inValue.Body = new TP2_Client.HotelReference.MakeReservationRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.id = id;
            inValue.Body.customer = customer;
            TP2_Client.HotelReference.MakeReservationResponse retVal = ((TP2_Client.HotelReference.HotelServiceSoap)(this)).MakeReservation(inValue);
            return retVal.Body.MakeReservationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP2_Client.HotelReference.MakeReservationResponse> TP2_Client.HotelReference.HotelServiceSoap.MakeReservationAsync(TP2_Client.HotelReference.MakeReservationRequest request) {
            return base.Channel.MakeReservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP2_Client.HotelReference.MakeReservationResponse> MakeReservationAsync(string login, string password, int id, TP2_Client.HotelReference.Customer customer) {
            TP2_Client.HotelReference.MakeReservationRequest inValue = new TP2_Client.HotelReference.MakeReservationRequest();
            inValue.Body = new TP2_Client.HotelReference.MakeReservationRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.id = id;
            inValue.Body.customer = customer;
            return ((TP2_Client.HotelReference.HotelServiceSoap)(this)).MakeReservationAsync(inValue);
        }
    }
}
