
package tp2.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConcreteHotelServiceService", targetNamespace = "http://service.server.tp2/", wsdlLocation = "http://localhost:3000/HotelService?wsdl")
public class ConcreteHotelServiceService
    extends Service
{

    private final static URL CONCRETEHOTELSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CONCRETEHOTELSERVICESERVICE_EXCEPTION;
    private final static QName CONCRETEHOTELSERVICESERVICE_QNAME = new QName("http://service.server.tp2/", "ConcreteHotelServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:3000/HotelService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONCRETEHOTELSERVICESERVICE_WSDL_LOCATION = url;
        CONCRETEHOTELSERVICESERVICE_EXCEPTION = e;
    }

    public ConcreteHotelServiceService() {
        super(__getWsdlLocation(), CONCRETEHOTELSERVICESERVICE_QNAME);
    }

    public ConcreteHotelServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONCRETEHOTELSERVICESERVICE_QNAME, features);
    }

    public ConcreteHotelServiceService(URL wsdlLocation) {
        super(wsdlLocation, CONCRETEHOTELSERVICESERVICE_QNAME);
    }

    public ConcreteHotelServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONCRETEHOTELSERVICESERVICE_QNAME, features);
    }

    public ConcreteHotelServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConcreteHotelServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConcreteHotelService
     */
    @WebEndpoint(name = "ConcreteHotelServicePort")
    public ConcreteHotelService getConcreteHotelServicePort() {
        return super.getPort(new QName("http://service.server.tp2/", "ConcreteHotelServicePort"), ConcreteHotelService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConcreteHotelService
     */
    @WebEndpoint(name = "ConcreteHotelServicePort")
    public ConcreteHotelService getConcreteHotelServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.server.tp2/", "ConcreteHotelServicePort"), ConcreteHotelService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONCRETEHOTELSERVICESERVICE_EXCEPTION!= null) {
            throw CONCRETEHOTELSERVICESERVICE_EXCEPTION;
        }
        return CONCRETEHOTELSERVICESERVICE_WSDL_LOCATION;
    }

}
